### ISSUE TITLE
Error - TextPart Class

### ISSUE THREAD

**Issue by CheungRCT** [gemini-api-php/client#26]
$response = $client->geminiPro()->generateContent(
    new TextPart('PHP in less than 100 chars')
);

results in TextPart Class not found

When following the screenshot program instead (the screen shot example has a different syntax from your documentation example:

$response = $client->geminiPro()->generateContent(
    new GeminiAPI\Resources\Parts\TextPart('PHP in less than 100 chars')
);

It calls with the following error:

PHP Fatal error:  Uncaught RuntimeException: Gemini API operation failed: operation=models/gemini-pro:generateContent, status_code=400,  response={
  "error": {
    "code": 400,
    "message": "Invalid JSON payload received. Unknown name \"{\"model\":\"models\\/gemini-pro\",\"contents\":[{\"parts\":[{\"text\":\"PHP in less than 100 chars\"}],\"role\":\"user\"}]}\": Cannot bind query parameter. Field '{\"model\":\"models\\/gemini-pro\",\"contents\":[{\"parts\":[{\"text\":\"PHP in less than 100 chars\"}],\"role\":\"user\"}]}' could not be found in request message.",
    "status": "INVALID_ARGUMENT",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.BadRequest",
        "fieldViolations": [
          {
            "description": "Invalid JSON payload received. Unknown name \"{\"model\":\"models\\/gemini-pro\",\"contents\":[{\"parts\":[{\"text\":\"PHP in less than 100 chars\"}],\"role\":\"user\"}]}\": Cannot bind query parameter. Field '{\"model\":\"models\\/gemini-pro\",\"contents\":[{\"parts\":[{\"text\":\"PHP in less than 100 chars\"}],\"role\":\"user\"}]}' could not be found in request message."
          }
        ]
      }
    ]
  }
}

**Comment by erdemkose** [comment]
Can you please share which version of the library and PHP you are using?

**Comment by erdemkose** [comment]
The problem should be solved in [v1.4.2](https://github.com/gemini-api-php/client/releases/tag/v1.4.2). Can you please update the library and try again?

**Comment by CheungRCT** [comment]
> Can you please share which version of the library and PHP you are using?
Previously I was using PHP 8.2.14  and the library version that I used was 1.3
