### ISSUE TITLE
How do I test this locally?

### ISSUE THREAD

**Issue by pdolinaj** [gemini-api-php/client#33]
When testing locally I get this error:

`PHP Fatal error:  Uncaught RuntimeException: Gemini API operation failed: operation=models/gemini-pro:generateContent, status_code=400,  response={
  "error": {
    "code": 400,
    "message": "User location is not supported for the API use without a billing account linked.",
    "status": "FAILED_PRECONDITION"
  }
}`

However, when I deploy to Live server, it all works fine.

How can I test this locally? Thank you

**Comment by erdemkose** [comment]
Gemini API can be used only in supported countries. See https://ai.google.dev/gemini-api/docs/available-regions

You can try to use an HTTP proxy or a VPN server by injecting your own HTTP client. See https://github.com/gemini-api-php/client?tab=readme-ov-file#using-your-own-http-client
